# Generated by Django 2.1.7 on 2019-02-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190216_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datecreate',
            new_name='dategenerated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='datecreate2',
            new_name='dategenerated2',
        ),
        migrations.AlterField(
            model_name='comment',
            name='n_vote',
            field=models.IntegerField(default=0),
        ),
    ]
