# Generated by Django 2.1.7 on 2019-02-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190216_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='x',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='y',
            new_name='comment',
        ),
    ]
