# Generated by Django 2.1.7 on 2019-02-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190218_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='_type',
        ),
    ]
