# Generated by Django 2.1.7 on 2019-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190227_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='n_vote',
            new_name='like',
        ),
    ]
