# Generated by Django 2.1.7 on 2019-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190228_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='pro.png', null=True, upload_to='profile'),
        ),
    ]
