# Generated by Django 2.1.7 on 2019-02-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
