# Generated by Django 2.1.7 on 2019-03-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextquestion',
            name='category',
            field=models.ForeignKey(default=0.0006603929337956083, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=0.0004955401387512388, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
    ]
